/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WaveRoulette } from "./WaveRoulette";

export { WaveRoulette__factory } from "./factories/WaveRoulette__factory";
